export type ScoutAddress = {
  block_number_balance_updated_at: number;
  coin_balance: string;
  creation_tx_hash: string;
  creator_address_hash: string;
  ens_domain_name: null | string;
  exchange_rate: null | string;
  has_beacon_chain_withdrawals: boolean;
  has_custom_methods_read: boolean;
  has_custom_methods_write: boolean;
  has_decompiled_code: boolean;
  has_logs: boolean;
  has_methods_read: boolean;
  has_methods_read_proxy: boolean;
  has_methods_write: boolean;
  has_methods_write_proxy: boolean;
  has_token_transfers: boolean;
  has_tokens: boolean;
  has_validated_blocks: boolean;
  hash: string;
  implementation_address: null | string;
  implementation_name: null | string;
  is_contract: boolean;
  is_verified: boolean;
  name: string;
  private_tags: string[];
  public_tags: string[];
  token: {
    address: string;
    circulating_market_cap: null | string;
    decimals: string;
    exchange_rate: null | string;
    holders: string;
    icon_url: null | string;
    name: string;
    symbol: string;
    total_supply: string;
    type: string;
    volume_24h: null | string;
  };
  watchlist_address_id: null | string;
  watchlist_names: string[];
};
